# Generated by Django 3.1.6 on 2021-02-11 08:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, upload_to='profiles/')),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_picture', models.ImageField(upload_to='vehicles/')),
                ('vehicle_color', models.CharField(max_length=100)),
                ('vehicle_kind', models.CharField(choices=[('car', 'Car'), ('jip', 'Jip'), ('truck', 'Truck')], default='car', max_length=40)),
                ('vehicle_type', models.CharField(choices=[('toyota', 'Toyota'), ('v8', 'V8'), ('bmw', 'BMW')], default='toyota', max_length=40)),
                ('number_of_passenger', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='carapp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='RequestRent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('start_date', models.DateField(verbose_name='Start Date(mm/dd/yyyy)')),
                ('return_date', models.DateField(verbose_name='Return Date(mm/dd/yyyy)')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='carapp.profile')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='carapp.vehicle')),
            ],
        ),
    ]
