# Generated by Django 3.1.6 on 2021-02-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status_of_vehicle',
            field=models.CharField(choices=[('available', 'Available'), ('busy', 'Busy')], default='available', max_length=40),
        ),
    ]
